#!/usr/bin/env bash
set -euo pipefail

BACKPACK_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$BACKPACK_ROOT"

print_banner() {
  cat <<'EOF'

╔══════════════════════════════════════════╗
║        AI Cloud Backpack — Setup        ║
╚══════════════════════════════════════════╝

EOF
}

pick_mode() {
  echo "How do you want to run Backpack?"
  echo "  1) Docker (recommended) — includes Tesseract OCR, ffmpeg, Vosk"
  echo "  2) Native (Rust binary) — faster rebuilds, no Docker overhead"
  echo ""
  read -rp "Choice [1]: " choice
  case "${choice:-1}" in
    1) MODE="docker" ;;
    2) MODE="native" ;;
    *) echo "Invalid choice, defaulting to Docker"; MODE="docker" ;;
  esac
  echo "→ Mode: $MODE"
}

check_docker() {
  if ! command -v docker &>/dev/null; then
    echo "Error: Docker is not installed."
    echo "Install it first: https://docs.docker.com/engine/install/"
    exit 1
  fi
  if ! docker compose version &>/dev/null; then
    echo "Error: Docker Compose is not available."
    echo "Install it first: https://docs.docker.com/compose/install/"
    exit 1
  fi
  echo "✓ Docker + Compose detected"
}

check_native_deps() {
  local missing=0

  if ! command -v cargo &>/dev/null; then
    echo "✗ Rust/Cargo not found — install from https://rustup.rs"
    missing=1
  else
    echo "✓ Cargo $(cargo --version | cut -d' ' -f2) detected"
  fi

  if command -v tesseract &>/dev/null; then
    echo "✓ Tesseract OCR detected"
  else
    echo "⚠ Tesseract OCR not found (optional — disables image OCR)"
  fi

  if command -v ffmpeg &>/dev/null; then
    echo "✓ ffmpeg detected"
  else
    echo "⚠ ffmpeg not found (optional — disables audio/video transcription)"
  fi

  if [ "$missing" -eq 1 ]; then
    echo ""
    echo "Install Rust first, then re-run setup.sh:"
    echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
  fi
}

pick_provider() {
  echo ""
  echo "Select your LLM provider:"
  echo "  1) OpenAI"
  echo "  2) Anthropic"
  echo "  3) Ollama (local)"
  echo "  4) Generic (OpenAI-compatible)"
  echo ""
  read -rp "Choice [1]: " choice
  case "${choice:-1}" in
    1) PROVIDER="openai" ;;
    2) PROVIDER="anthropic" ;;
    3) PROVIDER="ollama" ;;
    4) PROVIDER="generic" ;;
    *) echo "Invalid choice, defaulting to OpenAI"; PROVIDER="openai" ;;
  esac
  echo "→ Provider: $PROVIDER"
}

prompt_with_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_val="${3:-}"
  local val
  read -rp "$prompt_text [$default_val]: " val
  val="${val:-$default_val}"
  eval "$var_name=\"$val\""
}

configure_provider() {
  case "$PROVIDER" in
    openai)
      prompt_with_default LLM_MODEL       "Model"               "gpt-4o-mini"
      prompt_with_default LLM_API_KEY     "API key (sk-...)"    ""
      prompt_with_default EMBEDDING_MODEL "Embedding model"     "text-embedding-3-small"
      LLM_ENDPOINT="https://api.openai.com/v1"
      EMBEDDING_DIM=1536
      EMBEDDING_ENDPOINT=""
      EMBEDDING_API_KEY=""
      ;;
    anthropic)
      prompt_with_default LLM_MODEL       "Model"               "claude-3-haiku-20240307"
      prompt_with_default LLM_API_KEY     "Anthropic API key (sk-ant-...)" ""
      echo "  Note: Anthropic has no embedding API. Provide OpenAI-compatible embedding settings:"
      prompt_with_default EMBEDDING_ENDPOINT "Embedding endpoint" "https://api.openai.com/v1"
      prompt_with_default EMBEDDING_API_KEY  "Embedding API key"  ""
      prompt_with_default EMBEDDING_MODEL    "Embedding model"    "text-embedding-3-small"
      LLM_ENDPOINT="https://api.anthropic.com"
      EMBEDDING_DIM=1536
      ;;
    ollama)
      prompt_with_default LLM_ENDPOINT    "Endpoint"            "http://localhost:11434"
      prompt_with_default LLM_MODEL       "Model"               "llama3.2"
      prompt_with_default EMBEDDING_MODEL "Embedding model"     "nomic-embed-text"
      prompt_with_default EMBEDDING_DIM   "Embedding dim"       "768"
      LLM_API_KEY=""
      EMBEDDING_ENDPOINT=""
      EMBEDDING_API_KEY=""
      ;;
    generic)
      prompt_with_default LLM_ENDPOINT    "Endpoint"            "https://api.openai.com/v1"
      prompt_with_default LLM_API_KEY     "API key"             ""
      prompt_with_default LLM_MODEL       "Model"               "gpt-4o-mini"
      prompt_with_default EMBEDDING_MODEL "Embedding model"     "text-embedding-3-small"
      EMBEDDING_DIM=1536
      EMBEDDING_ENDPOINT=""
      EMBEDDING_API_KEY=""
      ;;
  esac
  prompt_with_default MAX_FILE_SIZE_MB "Max upload size (MB)" "100"
}

write_env() {
  cat > .env <<ENV
# Generated by setup.sh — $(date)
LLM_PROVIDER=${PROVIDER}
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL=${LLM_MODEL}
LLM_ENDPOINT=${LLM_ENDPOINT}
EMBEDDING_MODEL=${EMBEDDING_MODEL}
EMBEDDING_DIM=${EMBEDDING_DIM}
MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB}
UPLOAD_DIR=./uploads
DB_PATH=./data/backpack.db
ENV

  if [ -n "${EMBEDDING_ENDPOINT:-}" ]; then
    echo "EMBEDDING_ENDPOINT=${EMBEDDING_ENDPOINT}" >> .env
  fi
  if [ -n "${EMBEDDING_API_KEY:-}" ]; then
    echo "EMBEDDING_API_KEY=${EMBEDDING_API_KEY}" >> .env
  fi

  echo "✓ .env written"
}

create_dirs() {
  mkdir -p uploads data
  echo "✓ Directories ready: uploads/, data/"
}

mode_docker() {
  check_docker
  create_dirs
  echo ""
  echo "Starting Backpack with Docker Compose..."
  docker compose up -d
  echo ""
  echo "✓ Backpack is running at http://localhost:8080"
  echo ""
  echo "Try it:"
  echo "  curl http://localhost:8080/"
  echo "  curl -X POST http://localhost:8080/upload -F \"file=@some-document.pdf\""
  echo "  curl 'http://localhost:8080/search?q=your+query'"
}

mode_native() {
  check_native_deps
  create_dirs
  echo ""
  echo "Building Backpack (this may take a few minutes)..."
  cargo build --release
  echo ""
  echo "✓ Build complete — binary at target/release/backpack"
  echo ""
  if command -v tesseract &>/dev/null && command -v ffmpeg &>/dev/null; then
    EXTRA=" with full OCR + audio transcription"
  else
    EXTRA=""
  fi
  echo "Starting Backpack${EXTRA}..."
  echo ""
  ./target/release/backpack &
  BPID=$!
  sleep 2
  echo ""
  echo "✓ Backpack is running (PID $BPID) at http://localhost:8080"
  echo ""
  echo "Stop it with: kill $BPID"
  echo ""
  echo "Or run it yourself later:"
  echo "  cargo run --release"
  echo ""
  echo "Try it:"
  echo "  curl http://localhost:8080/"
  echo "  curl -X POST http://localhost:8080/upload -F \"file=@some-document.pdf\""
  echo "  curl 'http://localhost:8080/search?q=your+query'"
  wait $BPID 2>/dev/null || true
}

print_banner
pick_mode
pick_provider
configure_provider
echo ""
write_env
echo ""
case "$MODE" in
  docker) mode_docker ;;
  native) mode_native ;;
esac
